import pdfplumber

# predefined skills database
skills_db = [
"data structures",
"algorithms",
"object oriented programming",
"functional programming",
"operating systems",
"computer networks",
"database management systems",
"software engineering",
"design patterns",
"system design",
"distributed systems",
"parallel computing",
"high performance computing",
"cloud computing",
"edge computing",
"fog computing",
"virtualization",
"containerization",
"docker",
"kubernetes",
"devops",
"ci cd",
"git",
"github",
"gitlab",
"linux",
"unix",
"shell scripting",
"network security",
"cyber security",
"ethical hacking",
"penetration testing",
"cryptography",
"blockchain",
"smart contracts",
"internet of things",
"embedded systems",
"microcontrollers",
"arduino",
"raspberry pi",
"fpga",
"verilog",
"vhdl",
"digital electronics",
"analog electronics",
"signal processing",
"image processing",
"computer vision",
"natural language processing",
"speech recognition",
"deep learning",
"machine learning",
"reinforcement learning",
"data science",
"data analytics",
"big data",
"hadoop",
"spark",
"kafka",
"power bi",
"tableau",
"excel",
"statistics",
"probability",
"linear algebra",
"calculus",
"optimization",
"time series analysis",
"predictive modeling",
"feature engineering",
"model deployment",
"mlops",
"tensorflow",
"pytorch",
"keras",
"scikit learn",
"opencv",
"nlp transformers",
"bert",
"gpt models",
"flask",
"django",
"fastapi",
"rest api",
"graphql",
"web development",
"frontend development",
"backend development",
"full stack development",
"html",
"css",
"javascript",
"typescript",
"react",
"angular",
"vue",
"nodejs",
"expressjs",
"nextjs",
"redux",
"tailwind css",
"bootstrap",
"web security",
"progressive web apps",
"mobile app development",
"android development",
"ios development",
"flutter",
"react native",
"kotlin",
"swift",
"java",
"python",
"c",
"c++",
"c sharp",
"go",
"rust",
"php",
"sql",
"nosql",
"mongodb",
"firebase",
"postgresql",
"mysql",
"oracle db",
"database design",
"data warehousing",
"etl",
"data mining",
"information retrieval",
"search engines",
"recommendation systems",
"a b testing",
"user experience",
"user interface design",
"human computer interaction",
"game development",
"unity",
"unreal engine",
"augmented reality",
"virtual reality",
"mixed reality",
"digital twins",
"robotics",
"autonomous systems",
"control systems",
"pid controllers",
"mechatronics",
"cad",
"cam",
"cae",
"autoCAD",
"solidworks",
"catia",
"fusion 360",
"ansys",
"matlab",
"simulink",
"structural analysis",
"finite element analysis",
"computational fluid dynamics",
"fluid mechanics",
"thermodynamics",
"heat transfer",
"mass transfer",
"manufacturing processes",
"additive manufacturing",
"3d printing",
"cnc machining",
"quality control",
"lean manufacturing",
"six sigma",
"supply chain management",
"industrial engineering",
"operations research",
"project management",
"construction management",
"building information modeling",
"bim",
"surveying",
"geotechnical engineering",
"soil mechanics",
"structural engineering",
"transportation engineering",
"highway engineering",
"environmental engineering",
"water resources engineering",
"hydrology",
"irrigation engineering",
"wastewater treatment",
"solid waste management",
"green building",
"sustainable engineering",
"renewable energy",
"solar energy",
"wind energy",
"energy systems",
"power systems",
"electrical machines",
"power electronics",
"smart grids",
"battery technology",
"electric vehicles",
"automotive engineering",
"vehicle dynamics",
"internal combustion engines",
"hybrid vehicles",
"autonomous vehicles",
"aerodynamics",
"flight mechanics",
"propulsion systems",
"jet engines",
"rocket propulsion",
"spacecraft design",
"orbital mechanics",
"avionics",
"satellite communication",
"remote sensing",
"materials science",
"nanotechnology",
"polymer engineering",
"metallurgy",
"corrosion engineering",
"chemical engineering",
"process engineering",
"process control",
"chemical reaction engineering",
"petroleum engineering",
"refinery processes",
"biochemical engineering",
"bioprocess engineering",
"pharmaceutical engineering",
"food engineering"
]

def extract_skills(resume_path):
    text = ""
    # extract text from pdf
    with pdfplumber.open(resume_path) as pdf:
        for page in pdf.pages:
            text += page.extract_text()

    text = text.lower()
    found_skills = []

    # search skills
    for skill in skills_db:
        if skill in text:
            found_skills.append(skill)

    return found_skills
